
质检4.4集成NLP环境连调问题整理：
问题1、部署时es数据表没有加载导致词库同步有问题
问题2、缺少新规则生成算法依赖文件导致规则生成算法接口报错（hanlp依赖文件存放目录：/root/.hanlp/）
问题3、在问题2解决的基础上接口依然报错，经过排查发现hanlp预加载时需要调用外部请求，但是外部请求不被解析导致报错
    报错信息如下：
      File "/usr/local/python3/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/local/python3/lib/python3.6/urllib/request.py", line 1361, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/usr/local/python3/lib/python3.6/urllib/request.py", line 1320, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
    解决方案：
      在 /etc/resolv.conf 文件中加上 nameserver 114.114.114.114
问题4、项目settings.py中的质检回调配置没有修改成导致NLP任务执行成功后并没有回调通知成功
